[project]
name = "fastapi-sample"
version = "0.1.0"
description = "sample fastapi project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "jinja2>=3.1.6",
    "uvicorn>=0.40.0",
]
